# Generated by Django 4.2.11 on 2024-04-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingletonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Current value of the atomic integer.')),
            ],
            options={
                'verbose_name': 'Singleton Model',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('is_in', models.BooleanField(default=True)),
                ('transaction_block', models.IntegerField()),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('transaction_amount', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
