# Generated by Django 4.2.11 on 2024-05-01 03:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_transactions_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singletonmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={},
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='id',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this particular transaction', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='LIFO_Output',
            fields=[
                ('output_key', models.AutoField(primary_key=True, serialize=False)),
                ('new_price', models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True)),
                ('correct_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('transaction', models.ForeignKey(help_text='Reference to the transaction', on_delete=django.db.models.deletion.CASCADE, to='catalog.transactions')),
            ],
        ),
        migrations.CreateModel(
            name='LIFO_Input',
            fields=[
                ('input_key', models.AutoField(primary_key=True, serialize=False)),
                ('corrected_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('transaction', models.ForeignKey(help_text='Reference to the transaction', on_delete=django.db.models.deletion.CASCADE, to='catalog.transactions')),
            ],
        ),
        migrations.CreateModel(
            name='HIFO_Output',
            fields=[
                ('output_key', models.AutoField(primary_key=True, serialize=False)),
                ('new_price', models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True)),
                ('correct_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('transaction', models.ForeignKey(help_text='Reference to the transaction', on_delete=django.db.models.deletion.CASCADE, to='catalog.transactions')),
            ],
        ),
        migrations.CreateModel(
            name='HIFO_Input',
            fields=[
                ('input_key', models.AutoField(primary_key=True, serialize=False)),
                ('corrected_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('transaction', models.ForeignKey(help_text='Reference to the transaction', on_delete=django.db.models.deletion.CASCADE, to='catalog.transactions')),
            ],
        ),
        migrations.CreateModel(
            name='FIFO_Output',
            fields=[
                ('output_key', models.AutoField(primary_key=True, serialize=False)),
                ('new_price', models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True)),
                ('correct_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('transaction', models.ForeignKey(help_text='Reference to the transaction', on_delete=django.db.models.deletion.CASCADE, to='catalog.transactions')),
            ],
        ),
        migrations.CreateModel(
            name='FIFO_Input',
            fields=[
                ('input_key', models.AutoField(primary_key=True, serialize=False)),
                ('corrected_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('transaction', models.ForeignKey(help_text='Reference to the transaction', on_delete=django.db.models.deletion.CASCADE, to='catalog.transactions')),
            ],
        ),
    ]
