# Generated by Django 4.2.11 on 2024-05-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_singletonmodel_date_singletonmodel_prev_quatity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singletonmodel",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
