# Generated by Django 4.2.11 on 2024-05-01 23:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_alter_singletonmodel_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="singletonmodel",
            old_name="prev_quatity",
            new_name="prev_quantity",
        ),
    ]
