# Generated by Django 4.2.11 on 2024-05-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_rename_prev_quatity_singletonmodel_prev_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fifoi",
            name="corrected_amount",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fifor",
            name="correct_amount",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fifor",
            name="new_price",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hifoi",
            name="corrected_amount",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hifor",
            name="correct_amount",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hifor",
            name="new_price",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lifoi",
            name="corrected_amount",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lifor",
            name="correct_amount",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lifor",
            name="new_price",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="singletonmodel",
            name="prev_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_amount",
            field=models.DecimalField(decimal_places=9, max_digits=14),
        ),
    ]
